[Signature]
ID=00000000000000000000000000000000

[Version]
ID=G1701CA Version: C.00.00

[General]
Type=6
Inlet=0
Start Mode=0
Run Duration=39000
Solvent Delay=0
Tune File=hes_atune.u
Group Ions=1
Acq Mode=3
Gauges=2
Fast Scan=0
TID=0
EMSaver=0

[Zone 1]
ID=1
On=1
Soft Max=200
Set Point=150
Type=0

[Zone 2]
ID=0
On=1
Soft Max=250
Set Point=230
Type=0

[Zone 3]
ID=-1
On=0
Soft Max=0
Set Point=0
Type=0

[Ions 1]
Group Name=targets
Start Time=0
Resolution=0
Number of Ions=2
Ion 1=131.00,50
Group EMV Setting=0
Use Group EMV Setting=false
IonL1=
Ion 2=202.00,50
IonL2=

[Scan 1]
Start Time=0
Low Mass=100
High Mass=300
Threshold=100
Sampling=8
Low Plot 1=
Low Plot 2=
High Plot 1=
High Plot 2=

[Scan 2]

[Scan 3]

[Filters]
Mass Type=0
Mass Param=0
Mass Sigma=0
Time Type=0
Time Param=0
Time Sigma=0

[Plot]
Plot Type 1=0
Time Plot 1=0
Min Plot 1=0
Max Plot 1=0
Left Plot 1=0.000000
Top Plot 1=0.085653
Width Plot 1=0.520196
Height Plot 1=0.625268
Mode Plot 1=2
Left Plot 2=0.198286
Top Plot 2=0.197002
Width Plot 2=0.499388
Height Plot 2=0.501071
Mode Plot 2=2
X Gadget Pos 1=5
Y Gadget Pos 1=230
X Gadget Pos 2=130
Y Gadget Pos 2=230
Low Mass 1=1.6
High Mass 1=1050
Plot Label 1=

[Gauge1]
Type=2
ID=1
Display Type=0
Left Plot=380
Top Plot=230
Alarm Error=100.00
Alarm Warning=100.00
Alarm Minimum=0.00
Alarm Set=0

[Gauge2]
Type=2
ID=0
Display Type=0
Left Plot=255
Top Plot=230
Alarm Error=100.00
Alarm Warning=100.00
Alarm Minimum=0.00
Alarm Set=0

[Parameters]
ID 1=7
Mode 1=2
Value 1=1.000000
ID 2=-1
Mode 2=0
Value 2=0.000000

[Time Events]
Number Events=0
[SCIS]
H2FlowRate=0.13
Emission=10
SourceTemperature=230
QuadrupoleTemperature=150
Duration=1.3
StabilizationDuration=0.166666666666667
Filament=2
Mode=None
